# Generated by Django 6.0.2 on 2026-05-16 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("social", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="socialloginsetting",
            name="provider",
            field=models.CharField(
                choices=[("google-oauth2", "Google"), ("linkedin-oauth2", "LinkedIn")],
                max_length=20,
                unique=True,
            ),
        ),
    ]
