# Generated by Django 6.0.1 on 2026-01-09 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0002_resume_banner_image_resume_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='theme',
            field=models.CharField(choices=[('iPortfolio-1.0.0', 'Theme B - Iportfolio'), ('satner-master', 'Theme C - Satner'), ('meyawo-1.0.0', 'Theme E - Meyawo'), ('MyResume-1.0.0', 'Theme F - MyResume'), ('resume-bootstrap4-master', 'Theme G - resume')], default='meyawo-1.0.0', max_length=50),
        ),
    ]
