# Generated by Django 6.0.1 on 2026-01-10 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0003_resume_theme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='theme',
            field=models.CharField(choices=[('Style', 'Theme A - Style'), ('iPortfolio-1.0.0', 'Theme B - Iportfolio'), ('satner-master', 'Theme C - Satner'), ('jackson-master', 'Theme D - jackson'), ('meyawo-1.0.0', 'Theme E - Meyawo'), ('MyResume-1.0.0', 'Theme F - MyResume'), ('resume-bootstrap4-master', 'Theme G - resume'), ('FolioOne', 'Theme D - FolioOne')], default='meyawo-1.0.0', max_length=50),
        ),
    ]
