# Generated by Django 6.0.1 on 2026-01-10 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0004_alter_resume_theme'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='tags',
            field=models.CharField(blank=True, default='', help_text='Comma separated tags (e.g. Python, Django, React)', max_length=255),
        ),
    ]
