# Generated by Django 6.0.1 on 2026-01-10 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0005_resume_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='short_desc',
            field=models.TextField(blank=True, default='', help_text='Intro lines about yourself'),
        ),
        migrations.AddField(
            model_name='resume',
            name='tag_line',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
    ]
