# Generated by Django 6.0.1 on 2026-01-11 10:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0006_resume_short_desc_resume_tag_line'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResumeStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.PositiveIntegerField(help_text='Number value (e.g. 150)')),
                ('label', models.CharField(help_text='Label (e.g. Projects Completed)', max_length=100)),
                ('order', models.PositiveIntegerField(default=0)),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to='resume.resume')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
