# Generated by Django 6.0.1 on 2026-01-11 11:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0007_resumestat'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResumeSocial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('twitter', 'Twitter'), ('linkedin', 'LinkedIn'), ('github', 'GitHub'), ('instagram', 'Instagram'), ('facebook', 'Facebook'), ('youtube', 'YouTube'), ('website', 'Website'), ('other', 'Other')], max_length=30)),
                ('url', models.URLField()),
                ('icon_class', models.CharField(help_text='Icon class e.g. ti-twitter, ti-linkedin, fa fa-github', max_length=50)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='socials', to='resume.resume')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
