# Generated by Django 6.0.1 on 2026-01-11 11:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0008_resumesocial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResumeFloatingCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Text shown under icon (e.g. UI/UX Design)', max_length=100)),
                ('icon_class', models.CharField(help_text='Bootstrap icon class (e.g. bi bi-palette)', max_length=50)),
                ('card_class', models.CharField(help_text='CSS class (e.g. card-1, card-2)', max_length=50)),
                ('aos_animation', models.CharField(default='zoom-in', help_text='AOS animation (e.g. zoom-in, fade-up)', max_length=50)),
                ('aos_delay', models.PositiveIntegerField(default=300, help_text='Animation delay in ms (300, 400, 500)')),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='floating_cards', to='resume.resume')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
