# Generated by Django 6.0.1 on 2026-01-11 12:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0009_resumefloatingcard'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResumeJourney',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(help_text='Year or range e.g. 2019 or 2020-2022', max_length=10)),
                ('description', models.TextField()),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journeys', to='resume.resume')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ResumeSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('icon_class', models.CharField(help_text='Icon class e.g. bi bi-palette, bi bi-code-slash', max_length=50)),
                ('aos_animation', models.CharField(default='zoom-in', help_text='AOS animation type', max_length=30)),
                ('aos_delay', models.PositiveIntegerField(default=400, help_text='Animation delay in ms (400, 450, 500)')),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills_grid', to='resume.resume')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
