# Generated by Django 6.0.1 on 2026-01-11 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0012_certification'),
    ]

    operations = [
        migrations.AddField(
            model_name='resumestat',
            name='aos_delay',
            field=models.PositiveIntegerField(default=300),
        ),
        migrations.AddField(
            model_name='resumestat',
            name='icon_class',
            field=models.CharField(default='', help_text='Bootstrap icon class e.g. bi bi-trophy', max_length=50),
        ),
    ]
