# Generated by Django 6.0.1 on 2026-01-16 15:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0013_resumestat_aos_delay_resumestat_icon_class'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_desc', models.TextField(blank=True, default='', help_text='Intro lines about yourself')),
                ('icon_class', models.CharField(help_text='Bootstrap icon class e.g. bi bi-code-slash', max_length=50)),
                ('aos_delay', models.PositiveIntegerField(default=200)),
                ('order', models.PositiveIntegerField(default=0)),
                ('profession', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profession', to='resume.resumestat')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.AlterField(
            model_name='certification',
            name='certificate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certifications', to='resume.profession'),
        ),
    ]
