# Generated by Django 6.0.1 on 2026-01-16 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0014_profession_alter_certification_certificate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profession',
            name='profession',
        ),
    ]
