# Generated by Django 6.0.1 on 2026-01-16 15:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0015_remove_profession_profession'),
    ]

    operations = [
        migrations.AddField(
            model_name='profession',
            name='resume',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='professions', to='resume.resume'),
        ),
        migrations.AddField(
            model_name='profession',
            name='resume_stats',
            field=models.ManyToManyField(related_name='professions', to='resume.resumestat'),
        ),
        migrations.AddField(
            model_name='profession',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
