# Generated by Django 6.0.1 on 2026-01-16 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0016_profession_resume_profession_resume_stats_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='certification',
            name='certificate_image',
            field=models.ImageField(blank=True, null=True, upload_to='certificate/'),
        ),
    ]
