# Generated by Django 6.0.1 on 2026-01-16 16:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0017_certification_certificate_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Journey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('short_desc', models.TextField(blank=True, default='', help_text='Intro lines about yourself')),
                ('icon_class', models.CharField(help_text='Bootstrap icon class e.g. bi bi-code-slash', max_length=50)),
                ('aos_delay', models.PositiveIntegerField(default=200)),
                ('order', models.PositiveIntegerField(default=0)),
                ('resume', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='journey', to='resume.resume')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Excellence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('company', models.CharField(max_length=150)),
                ('date_range', models.CharField(max_length=50)),
                ('description', models.TextField(help_text='Short paragraph description')),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('journey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journey', to='resume.journey')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
