# Generated by Django 6.0.1 on 2026-01-17 08:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0018_journey_excellence'),
    ]

    operations = [
        migrations.AlterField(
            model_name='excellence',
            name='journey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='excellences', to='resume.journey'),
        ),
    ]
