# Generated by Django 6.0.1 on 2026-01-17 09:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0020_servicesection_service'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='servicesection',
            options={'ordering': ['order']},
        ),
        migrations.RemoveField(
            model_name='servicesection',
            name='is_active',
        ),
        migrations.AddField(
            model_name='servicesection',
            name='aos_delay',
            field=models.PositiveIntegerField(default=200),
        ),
        migrations.AddField(
            model_name='servicesection',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='servicesection',
            name='resume',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='servicesection', to='resume.resume'),
        ),
    ]
