# Generated by Django 6.0.1 on 2026-01-17 13:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0024_faqsection_faq'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Contact', max_length=100)),
                ('subtitle', models.TextField()),
                ('description', models.TextField(help_text='Left panel description')),
                ('location', models.TextField()),
                ('phone_numbers', models.TextField(help_text='One per line')),
                ('email_addresses', models.TextField(help_text='One per line')),
                ('receive_email_at', models.EmailField(help_text='Where contact form emails are sent', max_length=254)),
                ('is_active', models.BooleanField(default=True)),
                ('resume', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contact_sections', to='resume.resume')),
            ],
        ),
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='resume.contactsection')),
            ],
        ),
    ]
