# Generated by Django 6.0.2 on 2026-04-17 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resume", "0025_contactsection_contactmessage"),
    ]

    operations = [
        migrations.AddField(
            model_name="resume",
            name="pdf_template",
            field=models.CharField(
                choices=[
                    ("pdf1", "Modern Sidebar"),
                    ("pdf2", "Top Header"),
                    ("pdf3", "Minimal ATS"),
                ],
                default="pdf1",
                max_length=20,
            ),
        ),
    ]
