# Generated by Django 6.0.2 on 2026-04-18 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resume", "0026_resume_pdf_template"),
    ]

    operations = [
        migrations.AddField(
            model_name="resume",
            name="position",
            field=models.CharField(default="Senior technical lead", max_length=250),
        ),
    ]
