# Generated by Django 6.0.2 on 2026-04-18 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resume", "0027_resume_position"),
    ]

    operations = [
        migrations.AddField(
            model_name="resume",
            name="address",
            field=models.CharField(default="Noida,India", max_length=250),
        ),
    ]
