# Generated by Django 6.0.2 on 2026-04-18 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resume", "0028_resume_address"),
    ]

    operations = [
        migrations.AddField(
            model_name="resume",
            name="website",
            field=models.CharField(default="", max_length=250),
        ),
    ]
