# Generated by Django 6.0.2 on 2026-04-27 16:01

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("resume", "0030_alter_resume_pdf_template"),
    ]

    operations = [
        migrations.AlterField(
            model_name="resume",
            name="education",
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
        migrations.AlterField(
            model_name="resume",
            name="experience",
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
        migrations.AlterField(
            model_name="resume",
            name="short_desc",
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
        migrations.AlterField(
            model_name="resume",
            name="summary",
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
