# Generated by Django 6.0.2 on 2026-04-27 16:07

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("resume", "0031_alter_resume_education_alter_resume_experience_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="resume",
            name="education",
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name="Education"),
        ),
        migrations.AlterField(
            model_name="resume",
            name="experience",
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name="Experience"),
        ),
        migrations.AlterField(
            model_name="resume",
            name="short_desc",
            field=django_ckeditor_5.fields.CKEditor5Field(
                verbose_name="Short Description"
            ),
        ),
        migrations.AlterField(
            model_name="resume",
            name="skills",
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name="Skills"),
        ),
        migrations.AlterField(
            model_name="resume",
            name="summary",
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name="Summary"),
        ),
    ]
