# Generated by Django 6.0.2 on 2026-04-27 16:33

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("resume", "0032_alter_resume_education_alter_resume_experience_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contactsection",
            name="description",
            field=django_ckeditor_5.fields.CKEditor5Field(
                verbose_name="Left Pannel Description"
            ),
        ),
        migrations.AlterField(
            model_name="excellence",
            name="description",
            field=django_ckeditor_5.fields.CKEditor5Field(
                verbose_name="Short Paragraph Description"
            ),
        ),
        migrations.AlterField(
            model_name="journey",
            name="short_desc",
            field=django_ckeditor_5.fields.CKEditor5Field(
                verbose_name="Short Description"
            ),
        ),
        migrations.AlterField(
            model_name="profession",
            name="short_desc",
            field=django_ckeditor_5.fields.CKEditor5Field(
                verbose_name="Short Description"
            ),
        ),
        migrations.AlterField(
            model_name="resumejourney",
            name="description",
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name="Description"),
        ),
        migrations.AlterField(
            model_name="resumeskill",
            name="description",
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name="Description"),
        ),
        migrations.AlterField(
            model_name="service",
            name="description",
            field=django_ckeditor_5.fields.CKEditor5Field(
                verbose_name="Short Paragraph Description"
            ),
        ),
    ]
