# Generated by Django 6.0.2 on 2026-04-27 16:42

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("resume", "0033_alter_contactsection_description_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contactmessage",
            name="message",
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name="Message"),
        ),
        migrations.AlterField(
            model_name="contactsection",
            name="subtitle",
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name="Sub title"),
        ),
        migrations.AlterField(
            model_name="faq",
            name="answer",
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name="Answer"),
        ),
        migrations.AlterField(
            model_name="faq",
            name="question",
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name="Question"),
        ),
        migrations.AlterField(
            model_name="servicesection",
            name="subtitle",
            field=django_ckeditor_5.fields.CKEditor5Field(
                verbose_name="Service Sub Title"
            ),
        ),
        migrations.AlterField(
            model_name="testimonial",
            name="quote",
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name="Quote"),
        ),
    ]
