# Generated by Django 6.0.2 on 2026-05-16 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resume", "0035_resume_subdomain_resume_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="resume",
            name="email",
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name="resume",
            name="phone",
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
