# Generated by Django 6.0.2 on 2026-05-20 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resume", "0036_alter_resume_email_alter_resume_phone"),
    ]

    operations = [
        migrations.AddField(
            model_name="resume",
            name="moderated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="resume",
            name="moderation_reason",
            field=models.TextField(blank=True, null=True),
        ),
    ]
