# Generated by Django 6.0.2 on 2026-05-20 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resume", "0037_resume_moderated_at_resume_moderation_reason"),
    ]

    operations = [
        migrations.AddField(
            model_name="resume",
            name="moderation_status",
            field=models.CharField(default="approved", max_length=20),
        ),
    ]
