# Generated by Django 6.0.2 on 2026-05-20 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("resume", "0038_resume_moderation_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="resume",
            name="moderated_at",
        ),
        migrations.RemoveField(
            model_name="resume",
            name="moderation_reason",
        ),
        migrations.RemoveField(
            model_name="resume",
            name="moderation_status",
        ),
    ]
