# Generated by Django 6.0.2 on 2026-08-29 14:51

import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resume", "0039_remove_resume_moderated_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="resume",
            name="education",
            field=django_ckeditor_5.fields.CKEditor5Field(
                blank=True, verbose_name="Education"
            ),
        ),
        migrations.AlterField(
            model_name="resume",
            name="experience",
            field=django_ckeditor_5.fields.CKEditor5Field(
                blank=True, verbose_name="Experience"
            ),
        ),
        migrations.AlterField(
            model_name="resume",
            name="short_desc",
            field=django_ckeditor_5.fields.CKEditor5Field(
                blank=True, verbose_name="Short Description"
            ),
        ),
        migrations.AlterField(
            model_name="resume",
            name="skills",
            field=django_ckeditor_5.fields.CKEditor5Field(
                blank=True, verbose_name="Skills"
            ),
        ),
        migrations.AlterField(
            model_name="resume",
            name="summary",
            field=django_ckeditor_5.fields.CKEditor5Field(
                blank=True, verbose_name="Summary"
            ),
        ),
        migrations.AlterField(
            model_name="resume",
            name="website",
            field=models.CharField(blank=True, default="", max_length=250),
        ),
    ]
