# Generated by Django 6.0.2 on 2026-05-20 15:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AIProvider",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("openai", "OpenAI"),
                            ("gemini", "Google Gemini"),
                            ("anthropic", "Anthropic Claude"),
                            ("deepseek", "DeepSeek"),
                            ("grok", "Grok"),
                            ("azure_openai", "Azure OpenAI"),
                            ("ollama", "Ollama"),
                        ],
                        max_length=50,
                        unique=True,
                    ),
                ),
                ("is_active", models.BooleanField(default=False)),
                ("api_key", models.TextField(blank=True, null=True)),
                ("model_name", models.CharField(blank=True, max_length=255, null=True)),
                ("base_url", models.URLField(blank=True, null=True)),
                ("priority", models.PositiveIntegerField(default=1)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["priority"],
            },
        ),
        migrations.CreateModel(
            name="ModerationSetting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "moderation_enabled",
                    models.BooleanField(
                        default=True, help_text="Enable or disable moderation globally."
                    ),
                ),
                (
                    "keyword_filter_enabled",
                    models.BooleanField(
                        default=True, help_text="Enable or disable keyword filtering."
                    ),
                ),
                (
                    "bad_keywords",
                    models.TextField(
                        blank=True,
                        default="escort\nporn\ncall girl\nsex service\nadult service",
                        help_text="One keyword per line",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "active_provider",
                    models.ForeignKey(
                        blank=True,
                        help_text="AI provider used for moderation.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="moderation.aiprovider",
                    ),
                ),
            ],
            options={
                "verbose_name": "AI Moderation Setting",
                "verbose_name_plural": "AI Moderation Setting",
            },
        ),
    ]
