# Generated by Django 6.0.2 on 2026-08-29 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("moderation", "0003_expand_default_bad_keywords"),
    ]

    operations = [
        migrations.AlterField(
            model_name="moderationsetting",
            name="bad_keywords",
            field=models.TextField(
                blank=True,
                default="escort\nporn\npornographic\ncall girl\nsex service\nsex worker\nadult service\nadult content\nnude\nnudes\nnudity\nnaked photos\nxxx\nnsfw\nhardcore\nhookup\nonlyfans\ncamgirl\nwebcam sex\nbdsm\nfetish\nthreesome\ntwosome\ngangbang\nswinging\nswingers\nswapping partners\nwife swap\nsugar daddy\nsugar baby",
                help_text="One keyword per line. Deliberately excludes sexual-orientation or gender-identity words (e.g. 'gay', 'lesbian') since those are legitimate identity terms, not indicators of explicit content â\x80\x94 blocking them would wrongly flag genuine resumes/bios.",
            ),
        ),
    ]
