# Generated by Django 6.0.2 on 2026-05-11 17:49

import apps.whatsapp.models.otp_models
import django.db.models.deletion
import django_ckeditor_5.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="WhatsappMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "message_type",
                    models.CharField(
                        choices=[
                            ("welcome", "Welcome Message"),
                            ("confirmation", "Confirmation Message"),
                            ("otp", "OTP Message"),
                        ],
                        max_length=30,
                        unique=True,
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                (
                    "body",
                    django_ckeditor_5.fields.CKEditor5Field(
                        verbose_name="Whatsapp Message Body"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="WhatsAppSetting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        choices=[
                            ("wireweb", "WireWeb"),
                            ("meta", "Meta"),
                            ("twilio", "Twilio"),
                            ("gupshup", "Gupshup"),
                        ],
                        default="wireweb",
                        max_length=50,
                    ),
                ),
                ("api_key", models.TextField(blank=True, null=True)),
                ("session_id", models.TextField(blank=True, null=True)),
                ("access_token", models.TextField(blank=True, null=True)),
                (
                    "phone_number_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "whatsapp_number",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("app_name", models.CharField(blank=True, max_length=255, null=True)),
                ("enable_otp", models.BooleanField(default=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="OTPVerification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email_otp", models.CharField(blank=True, max_length=6, null=True)),
                ("whatsapp_otp", models.CharField(blank=True, max_length=6, null=True)),
                ("email_verified", models.BooleanField(default=False)),
                ("whatsapp_verified", models.BooleanField(default=False)),
                (
                    "verified_via",
                    models.CharField(
                        blank=True,
                        choices=[("email", "Email"), ("whatsapp", "WhatsApp")],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                ("is_completed", models.BooleanField(default=False)),
                ("email_attempts", models.IntegerField(default=0)),
                ("whatsapp_attempts", models.IntegerField(default=0)),
                (
                    "expires_at",
                    models.DateTimeField(
                        default=apps.whatsapp.models.otp_models.otp_expiry
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
