# Generated by Django 6.0.2 on 2026-05-11 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("whatsapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="otpverification",
            name="verified_via",
            field=models.CharField(
                blank=True,
                choices=[
                    ("email", "Email"),
                    ("whatsapp", "WhatsApp"),
                    ("gmail", "Google"),
                    ("linkedin", "LinkedIn"),
                ],
                max_length=20,
                null=True,
            ),
        ),
    ]
