# Generated by Django 6.0.2 on 2026-05-16 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("whatsapp", "0002_alter_otpverification_verified_via"),
    ]

    operations = [
        migrations.AlterField(
            model_name="otpverification",
            name="verified_via",
            field=models.CharField(
                blank=True,
                choices=[
                    ("email", "Email"),
                    ("whatsapp", "WhatsApp"),
                    ("google-oauth2", "Google"),
                    ("linkedin-oauth2", "LinkedIn"),
                ],
                max_length=20,
                null=True,
            ),
        ),
    ]
